version: '3.5'
services:
    test:
        image: php:8.0.8
        volumes:
            - ./bin:/home/bin
            - ./src:/home/src
            - ./specs:/home/specs
            - ./vendor:/home/vendor
        command: /home/bin/speckl
        working_dir: /home
